# Generated by Django 5.0.1 on 2024-04-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(default=0, verbose_name='価格'),
        ),
    ]
