# Generated by Django 5.0.4 on 2024-06-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
