# Generated by Django 5.0.4 on 2024-06-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_media_thumbnail_alter_media_link_alter_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
