# Generated by Django 5.0.4 on 2024-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_media_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title',
        ),
    ]
