# Generated by Django 5.0.4 on 2024-06-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_media_description_remove_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
