# Generated by Django 5.0.4 on 2024-06-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
