# Generated by Django 5.0.4 on 2024-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_media_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
