# Generated by Django 5.0.4 on 2024-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True, default='ここに備考を記入してください。', null=True, verbose_name='備考'),
        ),
    ]
