# Generated by Django 5.0.4 on 2024-08-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_rename_customer_name_customer_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
