# Generated by Django 5.0.4 on 2024-08-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_rename_customer_name_schedule_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hashed_line_user_id',
            new_name='hashed_id',
        ),
    ]
