# Generated by Django 5.0.4 on 2024-08-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_rename_hashed_line_user_id_customer_hashed_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hashed_id',
            new_name='hashed_line_user_id',
        ),
    ]
