# Generated by Django 5.0.4 on 2024-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_rename_hashed_id_customer_hashed_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
