# Generated by Django 5.0.4 on 2024-08-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_schedule_customer_name_schedule_hashed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='customer',
        ),
    ]
