# Generated by Django 5.0.4 on 2024-08-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_schedule_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
