# Generated by Django 5.0.4 on 2024-08-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_delete_customer'),
    ]

    operations = [
    ]
