# Generated by Django 5.0.4 on 2024-08-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_merge_0002_add_date_to_schedule_0023_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='temporary_booked_at',
        ),
    ]
