# Generated by Django 5.0.4 on 2024-08-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_schedule_temporary_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(max_length=255, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.CharField(max_length=255, verbose_name='開始時間'),
        ),
    ]
