# Generated by Django 5.0.4 on 2024-08-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_schedule_date_alter_schedule_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
