# Generated by Django 5.0.4 on 2024-08-21 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_remove_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 21), verbose_name='日付'),
            preserve_default=False,
        ),
    ]
